
public class C4_ExceptionDemo_22 {

	public static void main(String[] args) {
		
		try {
		int i=7;
		i=i/0;
		}
		
		catch(Exception e) {
			//e.printStackTrace();
			System.out.println("Error ");
		}
		finally {
			System.out.println(" finally alwayes execute");
		}
	}

}
