
public class C4_ExceptionDemo_22 {

	public static void main(String[] args) {
		
		try {
		int i=7;
		i=i/0;
		
		int a[]=new int[6];
		System.out.println(" out put is :"+i);
		}
		
		catch(ArithmeticException e) {
			//e.printStackTrace();//error print
			System.out.println("Error ");
		}
		finally {
			System.out.println(" finally alwayes execute");
		}
	}

}
